---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(jsonlite)
library(tidyverse)
library(plyr)
library(data.table)
library(readxl)
library(car)
library(caret)
library(MASS)
library(janitor)
library(sqldf)
library("na.tools")
library(mclust)
library(stargazer)
library(fmsb)
source("lib/viztools.R")
#load("NewestREnvironmentforWeatherProject.RData")
```

```{r}
weather_data <- read_csv("data/WeatherData_SummaryStatsAgg.csv") 
weather_data %>% summarise_at(vars(Temperature:Pressure), mean, na.rm = TRUE) -> weather_data_average
weather_data %>% group_by(cluster) %>% summarise_at(vars(Temperature:Pressure), median, na.rm = TRUE) -> weather_data_agg
weather_data %>% dplyr::select(Temperature:Pressure) -> weather_data_raw


weather_data_agg %>% dplyr::rename(raw_cluster = cluster) %>% mutate(Cluster = ifelse(raw_cluster==4, "A", ifelse(raw_cluster==6, "B",ifelse(raw_cluster==7,"C","")))) %>% filter(Cluster != "") -> weather_data_agg

weather_data_agg <- as.data.frame(weather_data_agg)
weather_data_agg -> weather_data_agg_with_cluster_col
weather_data_agg_with_cluster_col$raw_cluster <- NULL
rownames(weather_data_agg) <- weather_data_agg$Cluster
weather_data_agg$raw_cluster <- NULL
weather_data_agg$Cluster <- NULL

weather_data %>% summarise_at(vars(Temperature:Pressure), median, na.rm = TRUE) -> weather_data_median
weather_data_median$Cluster <- "League Median"
weather_data %>% summarise_at(vars(Temperature:Pressure), mean, na.rm = TRUE) -> weather_data_mean
weather_data_mean$Cluster <- "League Mean"
weather_data %>% summarise_at(vars(Temperature:Pressure), min, na.rm = TRUE) -> weather_data_min
weather_data_min$Cluster <- "League Min"
weather_data %>% summarise_at(vars(Temperature:Pressure), max, na.rm = TRUE) -> weather_data_max
weather_data_max$Cluster <- "League Max"


#WeatherData_SummaryStatsAgg_forViz <- filter(weather_data, cluster != 1 & cluster != 2 & cluster != 3 & cluster != 5 & cluster != 8)
#rownames(WeatherData_SummaryStatsAgg) <- 1:nrow(WeatherData_SummaryStatsAgg)
#Error: Can't transform a data frame with duplicate names.
#weather_data_agg %>% dplyr::select(Temperature:Pressure) -> weather_data_agg
```


The following will create side-by-side plots based upon the median values of the clusters and all data. 0=min of the data, 1=max of the data
```{r}

a <- "#FF5A5F"
b <- "#FFB400"
c <- "#007A87"
c <- "#007A87"
leagueMean <- "#8CE071"
#c(a,b,c)[i]
colMax <- function (x) { apply(x, MARGIN=c(2), max) }
colMin <- function (x) { apply(x, MARGIN=c(2), min) }
maxmin <- data.frame(max=colMax(rbind(weather_data_average,weather_data_agg,weather_data_max[-7])),min=colMin(rbind(weather_data_raw,weather_data_min[-7])))
average <- data.frame(rbind(maxmin$max,maxmin$min,weather_data_average))
radarchart(average)
#dev.new(width=10, height=10)
# Produce multiple plots ----
opar <- par() # save standard page layout settings for later restoration
# Define settings for plotting in a 3x4 grid, with appropriate margins:
#par(mar=rep(0.8,4))
#par(mar=c(5,1,5,1))
par(mfrow=c(1,3))
#par(pin=c(250,250))
weather_data_agg[c("Temperature","Pressure", "WindSpeed", "Precipitation","Humidity", "DewPoint")] -> weather_data_agg

# Iterate through the data, producing a radar-chart for each line
for (i in 1:nrow(weather_data_agg)) {
  toplot <- rbind(
    maxmin$max,
    maxmin$min,
    weather_data_median[-7],
    weather_data_agg[i,]
  )
  radarchart(
    toplot,
    pfcol = c(leagueMean,NA),
    pcol= c(NA,c(a,b,c)[i]),
    pty = 32, 
    plty = 1,
    plwd = 3,
    title = row.names(weather_data_agg[i,])
  )
}
#save 1551 x 576
#dev.off()
#dev.print(device=pdf,"visualizations/radar_charts.pdf",width=20,height=15) # Print the chart
#par <- par(opar) # restore standard par settings
```


```{r}
library(devtools)
#devtools::install_github("ricardo-bion/ggradar", dependencies = TRUE) # you may need to run this command twice

# Load the libraries
library(ggradar)
library(dplyr)
library(scales)

# First reload the original data, because we need "acteur" in the first column then do:


#the following scales based upon 0 being the min of the clusters, 1 being the max of the clusters
mutate_at(rbind(weather_data_agg_with_cluster_col,weather_data_mean)[c("Cluster", "Temperature","Pressure", "WindSpeed", "Precipitation","Humidity", "DewPoint")],vars(-Cluster),rescale) -> data_prep_scaled_average

#the following scales based upon 0 being the min of the data, 1 being the max of the data
mutate_at(rbind(weather_data_agg_with_cluster_col,weather_data_median,weather_data_min,weather_data_max)[c("Cluster", "Temperature","Pressure", "WindSpeed", "Precipitation","Humidity", "DewPoint")],vars(-Cluster),rescale) -> data_prep_scaled_all
head(data_prep_scaled_all,-2) -> data_prep_scaled_all #get rid of min/max

data_prep_scaled_average %>% ggradar() -> overlayed_radar
#print(overlayed_radar)
saveImage(overlayed_radar, widthPixels=1024, heightPixels=1024, filename = "visualizations/overlayed_radar.svg", dpi=300)
saveImage(overlayed_radar, widthPixels=1024, heightPixels=1024, filename = "visualizations/overlayed_radar.png", dpi=300)

data_prep_scaled_all %>% ggradar() -> overlayed_radar_all
#print(overlayed_radar_all)
saveImage(overlayed_radar_all, widthPixels=1024, heightPixels=1024, filename = "visualizations/overlayed_radar_all.svg", dpi=300)
saveImage(overlayed_radar_all, widthPixels=1024, heightPixels=1024, filename = "visualizations/overlayed_radar_all.png", dpi=300)

a <- "#FF5A5F"
b <- "#FFB400"
c <- "#007A87"
leagueMean <- "#8CE071"
#scale_fill_manual(values=c(a, b, c))
```



```{r}
data <- read.csv(text="acteur,theme1,theme2,theme3,theme4,theme5,theme6
acteur1,6,15,9,,,
acteur2,2,12,13,1,2,
acteur3,16,,5,4,5,
acteur4,12,3,14,,1,
acteur5,13,,17,,,
acteur6,11,2,10,6,1,
acteur7,4,8,14,2,,2
acteur8,13,5,12,,,
acteur9,21,,9,,,
acteur10,3,10,15,1,1,
acteur11,11,3,14,1,1,",stringsAsFactors=FALSE)
data[is.na(data)] <- 0
#https://ourednik.info/maps/2020/04/29/radar-charts-with-r/
# Put the line labels in rownames
rownames(data)<-data$acteur
data_raw <- data
#ggradar plot
mutate_at(data_raw,vars(-acteur),rescale) %>% ggradar()
data$acteur <- NULL

# Fetch minima and maxima of every column of the data-set ---- 
colMax <- function (x) { apply(x, MARGIN=c(2), max) }
colMin <- function (x) { apply(x, MARGIN=c(2), min) }
maxmin <- data.frame(max=colMax(data),min=colMin(data))

# Calculate the average profile ----
average <- data.frame(rbind(maxmin$max,maxmin$min,t(colMeans(data))))
colnames(average) <- colnames(data)
radarchart(average)

# Produce multiple plots ----
opar <- par() # save standard page layout settings for later restoration
# Define settings for plotting in a 3x4 grid, with appropriate margins:
par(mar=rep(0.8,4))
par(mfrow=c(3,4))
# Iterate through the data, producing a radar-chart for each line
for (i in 1:nrow(data)) {
  toplot <- rbind(
    maxmin$max,
    maxmin$min,
    average[3,],
    data[i,]
  )
  radarchart(
    toplot,
    pfcol = c("#99999980",NA),
    pcol= c(NA,2),
    pty = 32, 
    plty = 1,
    plwd = 2,
    title = row.names(data[i,])
  )
}
dev.print(device=pdf,"radarcharts.pdf",width=20,height=15) # Print the chart
par <- par(opar) # restore standard par settings
```

```{r}

WeatherData_SummaryStatsAgg_forViz <- read_csv("data/WeatherData_SummaryStatsAgg.csv") 

WeatherData_SummaryStatsAgg_forViz <- filter(as.data.frame(weather_data), cluster != 1 & cluster != 2 & cluster != 3 & cluster != 5 & cluster != 8)
WeatherData_SummaryStatsAgg_forViz %>% dplyr::rename(raw_cluster = cluster) %>% mutate(Cluster = ifelse(raw_cluster==4, 1, ifelse(raw_cluster==6, 2,ifelse(raw_cluster==7,3,NA)))) %>% filter(Cluster != "") -> WeatherData_SummaryStatsAgg_forViz


pairs(WeatherData_SummaryStatsAgg_forViz %>% dplyr::select(Temperature:Pressure), pch = 19,  cex = 0.5,
      
      col = c(a, b, c)[WeatherData_SummaryStatsAgg_forViz$Cluster],
      
      lower.panel=NULL)

par(xpd=TRUE)
legend("bottomleft", fill = c(a,b,c), legend = c("A","B","C"))
```
```{r}
library(GGally)
RunPcts_Stepwise_df <- read_csv("data/ParrellelCoordinateData.csv")
RunPcts_Stepwise_df %>% dplyr::rename(RawCluster = Cluster) %>% mutate(Cluster = ifelse(RawCluster == "Cluster_4", "A", ifelse(RawCluster == "Cluster_6", "B", "C"))) -> RunPcts_Stepwise_df
ggparcoord(RunPcts_Stepwise_df,scale="globalminmax",
           columns = 2:4, groupColumn = 6
) + ylab("Run Percentage") + xlab("Model") + theme_minimal() + scale_color_manual(values=c(a,b,c))
```

